<!DOCTYPE html>

<html lang="es"><head>
<meta charset="utf-8"/><meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<title>Admin Pagos y vencimientos</title>
<meta content="Maqueta de administración para Saltos del Laja Turístico." name="description"/>
<meta content="Saltos del Laja turístico, Salto del Laja turismo, alojamientos Salto del Laja, restaurantes Saltos del Laja, cabañas Salto del Laja, camping Salto del Laja, emprendimientos Salto del Laja, mapa turístico Saltos del Laja, qué hacer en Saltos del Laja, Región del Biobío, Los Ángeles Chile, Cabrero, Yumbel, turismo naturaleza Chile" name="keywords"/>
<link href="https://saltosdellajaturistico.cl/admin/pagos.php" rel="canonical"/>
<meta content="Admin Pagos y vencimientos" property="og:title"/><meta content="Maqueta de administración para Saltos del Laja Turístico." property="og:description"/><meta content="website" property="og:type"/><meta content="../assets/img/logo-header-saltos-del-laja.png" property="og:image"/>
<meta content="#004AAD" name="theme-color"/>
<link href="https://fonts.googleapis.com" rel="preconnect"/><link crossorigin="" href="https://fonts.gstatic.com" rel="preconnect"/><link href="https://fonts.googleapis.com/css2?family=Manrope:wght@300;400;500;600;700;800&amp;display=swap" rel="stylesheet"/>
<link href="../assets/css/styles.css" rel="stylesheet"/>
<script type="application/ld+json">{"@context":"https://schema.org","@type":"TouristDestination","name":"Saltos del Laja","description":"Guía turística de Saltos del Laja con alojamientos, restaurantes, emprendimientos, lugares para visitar, mapa y preguntas frecuentes.","address":{"@type":"PostalAddress","addressRegion":"Región del Biobío","addressCountry":"CL"},"touristType":["Familias","Parejas","Viajeros de ruta","Turismo naturaleza"]}</script>
<meta content="noindex, nofollow" name="robots"/><meta content="Saltos del Laja Turístico" name="author"/><meta content="Saltos del Laja Turístico" name="publisher"/><meta content="CL-BI" name="geo.region"/><meta content="Saltos del Laja, Región del Biobío, Chile" name="geo.placename"/><meta content="-37.216;-72.383" name="geo.position"/><meta content="-37.216, -72.383" name="ICBM"/><meta content="summary_large_image" name="twitter:card"/><meta content="Admin Pagos y vencimientos" name="twitter:title"/><meta content="../assets/img/logo-header-saltos-del-laja.png" name="twitter:image"/><link href="../assets/img/favicon-saltos-del-laja.png" rel="icon" type="image/png"/><meta content="es_CL" property="og:locale"/><link as="image" href="../assets/img/logo-header-saltos-del-laja.png" rel="preload"/><script id="seo-extra-schema" type="application/ld+json">{"@context": "https://schema.org", "@graph": [{"@type": "WebSite", "name": "Saltos del Laja Turístico", "url": "https://saltosdellajaturistico.cl/", "inLanguage": "es-CL", "potentialAction": {"@type": "SearchAction", "target": "https://saltosdellajaturistico.cl/?s={search_term_string}", "query-input": "required name=search_term_string"}}, {"@type": "Organization", "name": "Saltos del Laja Turístico", "url": "https://saltosdellajaturistico.cl/", "logo": "https://saltosdellajaturistico.cl/assets/img/logo-horizontal-oficial-saltos-del-laja.png", "sameAs": []}, {"@type": "TouristDestination", "name": "Saltos del Laja", "alternateName": ["Salto del Laja", "Saltos del Laja, Biobío"], "description": "Destino turístico de naturaleza en la Región del Biobío con cascadas, río, miradores, alojamientos, restaurantes, campings y emprendimientos locales.", "touristType": ["Familias", "Parejas", "Viajeros de ruta", "Turismo naturaleza", "Turismo local"], "containedInPlace": {"@type": "AdministrativeArea", "name": "Región del Biobío"}}]}</script></head><body><main class="content"><div class="container"><div class="panel"><div class="brand"><img alt="Logo" src="../assets/img/logo-header-saltos-del-laja.png" style="max-width:280px;max-height:80px;object-fit:contain;"/><div><strong>Saltos del Laja</strong><span>Admin</span></div></div><br/><h3>Pagos y vencimientos</h3><p>Maqueta base para panel administrador. En producción se recomienda conectar a PHP/MySQL, WordPress CPT o un backend con autenticación.</p><div class="actions"><a class="btn primary" href="../index.php">Volver al sitio</a><a class="btn green" href="crear-negocio.php">Crear publicación</a></div></div></div></main><a aria-label="Contactar por WhatsApp" class="whatsapp-float" href="https://wa.me/56900000000?text=Hola%2C%20necesito%20informaci%C3%B3n%20sobre%20Saltos%20del%20Laja%20Tur%C3%ADstico" rel="noopener" target="_blank"><span class="wa-dot">☏</span><span><small>Consulta directa</small><strong>WhatsApp</strong></span></a></body></html>